//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_watchlist_addresses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub watchlist_id: Option<i64>,
    pub watch_coin_input: Option<bool>,
    pub watch_coin_output: Option<bool>,
    pub watch_erc_20_input: Option<bool>,
    pub watch_erc_20_output: Option<bool>,
    pub watch_erc_721_input: Option<bool>,
    pub watch_erc_721_output: Option<bool>,
    pub watch_erc_1155_input: Option<bool>,
    pub watch_erc_1155_output: Option<bool>,
    pub notify_email: Option<bool>,
    pub notify_epns: Option<bool>,
    pub notify_feed: Option<bool>,
    pub notify_inapp: Option<bool>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub address_hash_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub name: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub address_hash: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_watchlist_notifications::Entity")]
    AccountWatchlistNotifications,
    #[sea_orm(
        belongs_to = "super::account_watchlists::Entity",
        from = "Column::WatchlistId",
        to = "super::account_watchlists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AccountWatchlists,
}

impl Related<super::account_watchlist_notifications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountWatchlistNotifications.def()
    }
}

impl Related<super::account_watchlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountWatchlists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
