//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account_watchlist_notifications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub watchlist_address_id: Option<i64>,
    pub direction: Option<String>,
    pub r#type: Option<String>,
    pub method: Option<String>,
    pub block_number: Option<i32>,
    pub amount: Option<Decimal>,
    pub tx_fee: Option<Decimal>,
    pub viewed_at: Option<DateTime>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub name: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub subject: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub from_address_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub to_address_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub transaction_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub subject_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub from_address_hash_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub to_address_hash_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub transaction_hash_hash: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_watchlist_addresses::Entity",
        from = "Column::WatchlistAddressId",
        to = "super::account_watchlist_addresses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AccountWatchlistAddresses,
}

impl Related<super::account_watchlist_addresses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountWatchlistAddresses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
