//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_name: String,
    pub user_address: String,
    pub user_email: String,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub fn find_by_user_name(user_name: &str) -> Select<Entity> {
        Self::find().filter(Column::UserName.eq(user_name))
    }

    pub fn find_by_user_address(user_address: &str) -> Select<Entity> {
        Self::find().filter(Column::UserAddress.eq(user_address))
    }
}
