[package]
name = "chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1" }
ethers-core = "2.0.3"
ethers-signers = "2.0.3"
rand = "0.8"
md5 = "0.7"
hex = "0.4"